frontend:
  deploymentname: frontend-deployment
  replicas: 1
  image: 735045504058.dkr.ecr.ap-south-1.amazonaws.com/frontend-repo:1.0.1
  servicename: frontend-service
  type: LoadBalancer

backend:
  deploymentname: backend-deployment
  replicas: 1
  image: 735045504058.dkr.ecr.ap-south-1.amazonaws.com/backend-repo:latest
  servicename: backend-service

db:
  secrets:
    name: db-secrets
    username: dmlqYXk=
    password: UGFzc3dvcmQxMjM=
